FROM python:3.11

WORKDIR /app

LABEL maintainer="kjboakye849@gmail.com"
LABEL description="Development image for the Hospitals GeoDjango API"

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install netcat-traditional gcc postgresql g++ python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev\
    && apt-get clean

RUN apt-get update \
    && apt-get install -y binutils libproj-dev gdal-bin python3-gdal libgdal-dev 

RUN pip3 install --upgrade pip
RUN pip3 install setuptools==58.0.0
RUN python3 -m pip install gdal==3.6.0

COPY Pipfile /app/Pipfile
COPY Pipfile.lock /app/Pipfile.lock
RUN pip3 install pipenv && pipenv install --dev --system --deploy


COPY . /app

